title:              "Cassey's 마이외이"
tagline:            "마케팅+이커머스+외국계+Etc.=마이외이"
email:              "dahae.jg@gmail.com"
description:        "외국계 이커머스 마케터가 전하는 외국계 회사생활+이커머스+마케팅 이야기"
author:             "정캐시"
baseurl:            "/"
url:                "https://cassey.kr"
locale:             "ko_KR"
thumbnail:          "/img/thumnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
