title:              "CASSEY'S 마이외이"
tagline:            "6년차 마케터의 마케팅◦이커머스◦외국계◦이야기"
email:              "dahae.jg@gmail.com"
description:        "외국계 6년차 이커머스 마케터가 전하는 외국계 회사 생활◦이커머스 운영◦디지털 마케팅 이야기"
author:             "정캐시"
baseurl:            "/"
url:                "https://cassey.kr"
locale:             "ko_KR"
thumbnail:          "/img/thumnail_new.png"

# Social Profiles
#twitter_username:   twitter_username
instagram_username: dahaejeong
facebook_username:  dahaejeong27
linkedin_username:  dahaejg

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: casseys-my-way
